import { relations } from "drizzle-orm"
import { pgEnum } from "drizzle-orm/pg-core"
import { createTable } from "../lib/utils"
import { lessons } from "./lessons"
import { playerExercisePlays } from "./player-exercise-plays"

export const exerciseTypeEnum = pgEnum("exercise_type", [
	"quiz",
	"matching",
	"fill_blank",
	"multiple_choice",
])

export const exerciseDifficultyLevelEnum = pgEnum("exercise_difficulty_level", [
	"easy",
	"medium",
	"hard",
])

export const exercises = createTable("exercise", (d) => ({
	id: d.uuid().primaryKey().defaultRandom(),
	lessonId: d
		.uuid("lesson_id")
		.notNull()
		.references(() => lessons.id),
	title: d.varchar({ length: 255 }).notNull(),
	exerciseType: d
		.varchar("exercise_type", { length: 50 })
		.$type<"quiz" | "matching" | "fill_blank" | "multiple_choice">()
		.notNull(),
	content: d.jsonb("content").$type<Record<string, unknown>>().notNull(),
	difficultyLevel: d
		.varchar("difficulty_level", { length: 50 })
		.$type<"easy" | "medium" | "hard">()
		.notNull(),
	isAutoGenerated: d.boolean("is_auto_generated").default(false).notNull(),
	orderIndex: d.integer("order_index").notNull(),
	createdAt: d
		.timestamp("created_at", { withTimezone: true })
		.$defaultFn(() => new Date())
		.notNull(),
}))

export const exercisesRelations = relations(exercises, ({ one, many }) => ({
	lesson: one(lessons, {
		fields: [exercises.lessonId],
		references: [lessons.id],
	}),
	plays: many(playerExercisePlays),
}))
