import { relations } from "drizzle-orm"
import { createTable } from "../lib/utils"
import { units } from "./units"
import { exercises } from "./exercises"
import { playerLessonProgress } from "./player-lesson-progress"

export const lessons = createTable("lesson", (d) => ({
	id: d.uuid().primaryKey().defaultRandom(),
	unitId: d
		.uuid("unit_id")
		.notNull()
		.references(() => units.id),
	title: d.varchar({ length: 255 }).notNull(),
	orderIndex: d.integer("order_index").notNull(),
	isAutoGenerated: d.boolean("is_auto_generated").default(false).notNull(),
	createdAt: d
		.timestamp("created_at", { withTimezone: true })
		.$defaultFn(() => new Date())
		.notNull(),
}))

export const lessonsRelations = relations(lessons, ({ one, many }) => ({
	unit: one(units, {
		fields: [lessons.unitId],
		references: [units.id],
	}),
	exercises: many(exercises),
	progress: many(playerLessonProgress),
}))
