import { relations } from "drizzle-orm"
import { createTable } from "../lib/utils"
import { kurios } from "./kurios"
import { lessons } from "./lessons"

export const units = createTable("unit", (d) => ({
	id: d.uuid().primaryKey().defaultRandom(),
	kurioId: d
		.uuid("kurio_id")
		.notNull()
		.references(() => kurios.id),
	title: d.varchar({ length: 255 }).notNull(),
	orderIndex: d.integer("order_index").notNull(),
	isAutoGenerated: d.boolean("is_auto_generated").default(false).notNull(),
	createdAt: d
		.timestamp("created_at", { withTimezone: true })
		.$defaultFn(() => new Date())
		.notNull(),
}))

export const unitsRelations = relations(units, ({ one, many }) => ({
	kurio: one(kurios, {
		fields: [units.kurioId],
		references: [kurios.id],
	}),
	lessons: many(lessons),
}))
