import { and, eq } from "drizzle-orm"
import { z } from "zod"
import { generateGameContent } from "@/lib/ai/game-generator"
import { createTRPCRouter, protectedProcedure } from "@/server/api/trpc"
import {
	gameAttempts,
	games,
	kurios,
	unitProgress,
	units,
} from "@/server/db/schemas"

export const gameRouter = createTRPCRouter({
	submitAnswer: protectedProcedure
		.input(
			z.object({
				gameId: z.string().uuid(),
				userAnswer: z.record(z.unknown()),
				isCorrect: z.boolean(),
				score: z.number().int(),
				timeSpent: z.number().int(),
			}),
		)
		.mutation(async ({ ctx, input }) => {
			// Get user profile ID
			const userProfile = await ctx.db.query.userProfiles.findFirst({
				where: (profiles, { eq }) => eq(profiles.userId, ctx.user.id),
			})

			if (!userProfile) {
				throw new Error("User profile not found")
			}

			// Record the attempt
			await ctx.db.insert(gameAttempts).values({
				playerId: userProfile.id,
				gameId: input.gameId,
				userAnswer: input.userAnswer,
				isCorrect: input.isCorrect,
				score: input.score,
				timeSpent: input.timeSpent,
			})

			// Update unit progress
			const game = await ctx.db.query.games.findFirst({
				where: (games, { eq }) => eq(games.id, input.gameId),
				with: {
					unit: {
						with: {
							games: true,
						},
					},
				},
			})

			if (game) {
				const totalGames = game.unit.games.length

				const existingProgress = await ctx.db.query.unitProgress.findFirst({
					where: (progress, { eq, and }) =>
						and(
							eq(progress.playerId, userProfile.id),
							eq(progress.unitId, game.unitId),
						),
				})

				if (existingProgress) {
					await ctx.db
						.update(unitProgress)
						.set({
							completedGames: existingProgress.completedGames + 1,
							isCompleted:
								existingProgress.completedGames + 1 >=
								existingProgress.totalGames,
							lastPlayedAt: new Date(),
							updatedAt: new Date(),
						})
						.where(
							and(
								eq(unitProgress.playerId, userProfile.id),
								eq(unitProgress.unitId, game.unitId),
							),
						)
				} else {
					// Create new progress record if it doesn't exist
					await ctx.db.insert(unitProgress).values({
						playerId: userProfile.id,
						unitId: game.unitId,
						completedGames: 1,
						totalGames,
						isCompleted: 1 >= totalGames,
						lastPlayedAt: new Date(),
					})
				}
			}

			return { success: true }
		}),

	getAllUnitProgress: protectedProcedure
		.input(z.object({ unitIds: z.array(z.string().uuid()) }))
		.query(async ({ ctx, input }) => {
			const userProfile = await ctx.db.query.userProfiles.findFirst({
				where: (profiles, { eq }) => eq(profiles.userId, ctx.user.id),
			})

			if (!userProfile) {
				throw new Error("User profile not found")
			}

			if (input.unitIds.length === 0) {
				return []
			}

			const progress = await ctx.db.query.unitProgress.findMany({
				where: (progress, { eq, and, inArray }) =>
					and(
						eq(progress.playerId, userProfile.id),
						inArray(progress.unitId, input.unitIds),
					),
			})

			return progress
		}),

	generateGame: protectedProcedure
		.input(
			z.object({
				kurioId: z.string().uuid(),
			}),
		)
		.mutation(async ({ ctx, input }) => {
			// Get kurio with resources
			const kurio = await ctx.db.query.kurios.findFirst({
				where: (kurios, { eq }) => eq(kurios.id, input.kurioId),
				with: {
					resources: true,
				},
			})

			if (!kurio) {
				throw new Error("Kurio not found")
			}

			if (kurio.userId !== ctx.user.id) {
				throw new Error("Unauthorized")
			}

			// Generate game content using AI
			const gameContent = await generateGameContent({
				resources: kurio.resources.map((r) => ({
					resourceType: r.resourceType,
					resourceContent: r.resourceContent ?? undefined,
					resourceFileUrl: r.resourceFileUrl ?? undefined,
				})),
				aiModel: kurio.aiModel,
			})

			// Create units and games directly
			let totalGames = 0

			for (const unitData of gameContent.units) {
				const [unit] = await ctx.db
					.insert(units)
					.values({
						kurioId: kurio.id,
						title: unitData.title,
						orderIndex: gameContent.units.indexOf(unitData),
						isAutoGenerated: true,
					})
					.returning()

				if (!unit) {
					throw new Error("Failed to create unit")
				}

				for (const gameData of unitData.games) {
					await ctx.db.insert(games).values({
						unitId: unit.id,
						title: gameData.title,
						gameType: gameData.gameType,
						content: gameData.content,
						difficultyLevel: gameData.difficultyLevel,
						orderIndex: unitData.games.indexOf(gameData),
						isAutoGenerated: true,
					})
					totalGames++
				}
			}

			// Update kurio status and total games
			await ctx.db
				.update(kurios)
				.set({
					status: "ready",
					totalExercises: totalGames,
					updatedAt: new Date(),
				})
				.where(eq(kurios.id, kurio.id))

			return { success: true, totalGames }
		}),
})
