import { z } from "zod"
import { eq, and } from "drizzle-orm"

import { createTRPCRouter, protectedProcedure } from "@/server/api/trpc"
import {
	exercises,
	lessons,
	units,
	kurios,
	playerExercisePlays,
	playerLessonProgress,
} from "@/server/db/schemas"
import { generateGameContent } from "@/lib/ai/game-generator"

export const gameRouter = createTRPCRouter({
	getExercise: protectedProcedure
		.input(z.object({ exerciseId: z.string().uuid() }))
		.query(async ({ ctx, input }) => {
			const exercise = await ctx.db.query.exercises.findFirst({
				where: (exercises, { eq }) => eq(exercises.id, input.exerciseId),
				with: {
					lesson: {
						with: {
							unit: {
								with: {
									kurio: true,
								},
							},
						},
					},
				},
			})

			if (!exercise) {
				throw new Error("Exercise not found")
			}

			return exercise
		}),

	submitAnswer: protectedProcedure
		.input(
			z.object({
				exerciseId: z.string().uuid(),
				userAnswer: z.record(z.unknown()),
				isCorrect: z.boolean(),
				score: z.number().int(),
				timeSpent: z.number().int(),
			}),
		)
		.mutation(async ({ ctx, input }) => {
			// Get user profile ID
			const userProfile = await ctx.db.query.userProfiles.findFirst({
				where: (profiles, { eq }) => eq(profiles.userId, ctx.user.id),
			})

			if (!userProfile) {
				throw new Error("User profile not found")
			}

			// Record the play
			await ctx.db.insert(playerExercisePlays).values({
				playerId: userProfile.id,
				exerciseId: input.exerciseId,
				userAnswer: input.userAnswer,
				isCorrect: input.isCorrect,
				score: input.score,
				timeSpent: input.timeSpent,
			})

			// Update lesson progress
			const exercise = await ctx.db.query.exercises.findFirst({
				where: (exercises, { eq }) => eq(exercises.id, input.exerciseId),
			})

			if (exercise) {
				const existingProgress = await ctx.db.query.playerLessonProgress.findFirst({
					where: (progress, { eq, and }) =>
						and(
							eq(progress.playerId, userProfile.id),
							eq(progress.lessonId, exercise.lessonId),
						),
				})

				if (existingProgress) {
					await ctx.db
						.update(playerLessonProgress)
						.set({
							completedExercises: existingProgress.completedExercises + 1,
							isCompleted:
								existingProgress.completedExercises + 1 >=
								existingProgress.totalExercises,
							lastPlayedAt: new Date(),
							updatedAt: new Date(),
						})
						.where(
							and(
								eq(playerLessonProgress.playerId, userProfile.id),
								eq(playerLessonProgress.lessonId, exercise.lessonId),
							),
						)
				}
			}

			return { success: true }
		}),

	getLessonProgress: protectedProcedure
		.input(z.object({ lessonId: z.string().uuid() }))
		.query(async ({ ctx, input }) => {
			const userProfile = await ctx.db.query.userProfiles.findFirst({
				where: (profiles, { eq }) => eq(profiles.userId, ctx.user.id),
			})

			if (!userProfile) {
				throw new Error("User profile not found")
			}

			const progress = await ctx.db.query.playerLessonProgress.findFirst({
				where: (progress, { eq, and }) =>
					and(
						eq(progress.playerId, userProfile.id),
						eq(progress.lessonId, input.lessonId),
					),
			})

			return progress
		}),

	generateGame: protectedProcedure
		.input(
			z.object({
				kurioId: z.string().uuid(),
			}),
		)
		.mutation(async ({ ctx, input }) => {
			// Get kurio with resources
			const kurio = await ctx.db.query.kurios.findFirst({
				where: (kurios, { eq }) => eq(kurios.id, input.kurioId),
				with: {
					resources: true,
				},
			})

			if (!kurio) {
				throw new Error("Kurio not found")
			}

			if (kurio.userId !== ctx.user.id) {
				throw new Error("Unauthorized")
			}

			// Generate game content using AI
			const gameContent = await generateGameContent({
				resources: kurio.resources.map((r) => ({
					resourceType: r.resourceType,
					resourceContent: r.resourceContent ?? undefined,
					resourceFileUrl: r.resourceFileUrl ?? undefined,
				})),
				difficultyLevel: kurio.difficultyLevel,
				aiModel: kurio.aiModel,
			})

			// Create units, lessons, and exercises
			let totalExercises = 0

			for (const unitData of gameContent.units) {
				const [unit] = await ctx.db
					.insert(units)
					.values({
						kurioId: kurio.id,
						title: unitData.title,
						orderIndex: gameContent.units.indexOf(unitData),
						isAutoGenerated: true,
					})
					.returning()

				for (const lessonData of unitData.lessons) {
					const [lesson] = await ctx.db
						.insert(lessons)
						.values({
							unitId: unit.id,
							title: lessonData.title,
							orderIndex: unitData.lessons.indexOf(lessonData),
							isAutoGenerated: true,
						})
						.returning()

					for (const exerciseData of lessonData.exercises) {
						await ctx.db.insert(exercises).values({
							lessonId: lesson.id,
							title: exerciseData.title,
							exerciseType: exerciseData.exerciseType,
							content: exerciseData.content,
							difficultyLevel: exerciseData.difficultyLevel,
							orderIndex: lessonData.exercises.indexOf(exerciseData),
							isAutoGenerated: true,
						})
						totalExercises++
					}
				}
			}

			// Update kurio status and total exercises
			await ctx.db
				.update(kurios)
				.set({
					status: "ready",
					totalExercises,
					updatedAt: new Date(),
				})
				.where(eq(kurios.id, kurio.id))

			return { success: true, totalExercises }
		}),
})

